### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by ibelem** [intel/web-ai-showcase#31]
We may need a contributing guidelines (CONTRIBUTING.md) in the future. @NingW101  @gyagp

**Comment by gyagp** [comment]
+1

**Comment by NingW101** [comment]
1. Add linting check(including formatting check)
https://github.com/intel/web-ai-showcase/pull/33

2. Integrate into CI 
    - linting check
    - build process check

3. Update `CONTRIBUTING.md` for the guidelines to make contribution

**Comment by ibelem** [comment]
Closed via https://github.com/intel/web-ai-showcase/pull/36
